#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-FEC
version:      0.02
version_from: FEC.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
